
Error: Python: Traceback (most recent call last):
  File "\Text", line 30, in <module>
AttributeError: 'Scene' object has no attribute 'directory'
