Error: Python: Traceback (most recent call last):
  File "\Text", line 11, in <module>
TypeError: argument of type 'bpy_lib' is not iterable
